name: microapp-store-design
base_image: language/static
team: merc
slack_channel: merc-notifications
processes:
  web:
    cmd: nginx >> $LOG_DIR/nginx_startup_plain.log 2>&1
    internal_domain_prefix: 'microapp-store-design'
    external_domain_prefix: 'microapp-store-design'
    public: true
    health_check:
      http:
        port: 8080
        # Required for http, https, and TCP. The URL on your application which the health check resides.
        endpoint: /manifest.json
    port: 8080
    alert_via:
      - slack
      - pagerduty
