language: node_js

node_js:
  - "8.11"

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install

services:
  - docker

sudo: required

env:
  matrix:
    - CREATE_CONTAINER=true
    - RUN_TESTS=true

matrix:
  fast_finish: true
  allow_failures:
    env: CREATE_CONTAINER=true

script:
  - ./.travis.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://launchbay.bigcommerce.net/api/v1/build_results/store-design
