language: node_js

node_js:
  - "10.9.0"

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install

services:
  - docker

sudo: required

env:
  matrix:
    - CREATE_CONTAINER=true
    - RUN_TESTS=true
    - PREREQ=true

matrix:
  fast_finish: true

script:
  - ./.travis.sh

notifications:
  email: true
  webhooks:
    urls:
      - https://launchbay.bigcommerce.net/api/v1/build_results/store-design
